{
  pkgs,
  inputs,
  ...
}: {
  environment.systemPackages = with pkgs; [
    inputs.nix-inspect.packages.${pkgs.system}.default
    # vim
    #cargo-watch
    #cargo-spellcheck
    alejandra
    keyd
    cheat
    nitch
    vimiv-qt
    qalculate-gtk
    just
    inotify-tools
    wlroots
    evcxr # rust repl
    rustup
    vulkan-loader
    vulkan-validation-layers
    vulkan-tools
    amdvlk
    wget
    killall
    eza
    cmatrix
    lolcat
    efibootmgr
    htop
    pokemon-colorscripts-mac
    libvirt
    lxqt.lxqt-policykit
    lm_sensors
    unzip
    unrar
    libnotify
    v4l-utils
    ydotool
    duf
    ncdu
    pciutils
    ffmpeg
    socat
    ripgrep
    lshw
    pkg-config
    nwg-look
    meson
    ninja
    virt-viewer # graphical consol client for qemu
    appimage-run
    inxi
    nix-prefetch-git
    nix-prefetch-github
    libgcc
    gcc
    gnumake
    chafa
    file-roller
    imv
    mpv
    gimp
    tree
    cachix
    dconf2nix
    greetd.tuigreet
    lazygit
    zig_0_12
    unipicker
    nvtopPackages.amd
    dmidecode
    _7zz
    p7zip
    alsa-utils
    nix-diff
    linuxKernel.packages.linux_zen.cpupower
    tradingview
    dconf-editor
    rose-pine-cursor
    openssl
    pkg-config
    go
    transmission_4-gtk
  ];
}
